//! Candle port of the DSpark drafter (DeepSpec Qwen3DSparkModel inference).
//!
//! Mirrors deepspec/modeling/dspark/qwen3/modeling.py exactly: a small
//! full-attention transformer whose K/V are the fused target context
//! prepended to the draft block, per-head QK-RMSNorm applied before RoPE,
//! bidirectional attention with no mask, a low-rank Markov bias sampled left
//! to right, and a linear confidence head over [h_k ; W1[x_{k-1}]].
//!
//! Verified against a fixture generated by the pinned training environment
//! (`dspark-drafter-parity`); the drafter keeps per-layer caches of the
//! projected context so multi-round runners only project newly committed
//! positions.

use std::fs::File;
use std::path::Path;

use anyhow::{Context, Result};
use candle::op::BackpropOp;
use candle::quantized::{GgmlDType, QStorage};
use candle::{DType, Device, IndexOp, MetalStorage, Module, Storage, Tensor, D};
use candle_nn::{Linear, VarBuilder};
use serde::Deserialize;

use crate::quantized_linear::MixedLinear;
use crate::qwen35::TruncatableKvCache;

#[derive(Clone, Debug, Deserialize)]
pub struct DsparkRopeParameters {
    pub rope_theta: f64,
}

fn default_markov_head_type() -> String {
    "vanilla".to_string()
}
fn default_true() -> bool {
    true
}
fn default_min_log_snr() -> f64 {
    -9.0
}
fn default_max_log_snr() -> f64 {
    9.0
}

#[derive(Clone, Debug, Deserialize)]
pub struct DsparkConfig {
    pub vocab_size: usize,
    pub hidden_size: usize,
    pub intermediate_size: usize,
    pub num_hidden_layers: usize,
    pub num_attention_heads: usize,
    pub num_key_value_heads: usize,
    pub head_dim: usize,
    pub rms_norm_eps: f64,
    pub block_size: usize,
    pub mask_token_id: u32,
    pub markov_rank: usize,
    pub target_layer_ids: Vec<usize>,
    pub rope_parameters: DsparkRopeParameters,
    // Head-variant switches: the port implements exactly vanilla Markov +
    // markov-feature confidence; loading must fail loudly on anything else
    // rather than ignore gate_proj/joint_proj tensors and drift silently.
    #[serde(default = "default_markov_head_type")]
    pub markov_head_type: String,
    #[serde(default = "default_true")]
    pub enable_confidence_head: bool,
    #[serde(default = "default_true")]
    pub confidence_head_with_markov: bool,
    // GIDD log-SNR conditioning (diffusion-style timestep embed added to the
    // draft-block embedding). Off in the safetensors round-4 drafter; the
    // Bonsai GGUF drafter enables it. When on, log_snr_fc1/fc2 must be present.
    #[serde(default)]
    pub log_snr_conditioning: bool,
    #[serde(default = "default_min_log_snr")]
    pub min_log_snr: f64,
    #[serde(default = "default_max_log_snr")]
    pub max_log_snr: f64,
}

impl DsparkConfig {
    pub fn from_dir(dir: &Path) -> Result<Self> {
        let path = dir.join("config.json");
        let file =
            File::open(&path).with_context(|| format!("open drafter config {}", path.display()))?;
        serde_json::from_reader(std::io::BufReader::new(file))
            .with_context(|| format!("parse drafter config {}", path.display()))
    }

    /// Derive the drafter config from a `dspark.*`-namespaced GGUF (the shipped
    /// Bonsai drafter). Mirrors the prism llama.cpp arch key names.
    pub fn from_gguf(gguf: &crate::gguf::GgufFile) -> Result<Self> {
        use crate::gguf::{md_bool, md_f64, md_u32, md_u32_array, md_usize};
        let c = gguf.content();
        let log_snr = md_bool(c, "dspark.dspark.log_snr_conditioning").unwrap_or(false);
        Ok(Self {
            vocab_size: md_usize(c, "dspark.vocab_size")?,
            hidden_size: md_usize(c, "dspark.embedding_length")?,
            intermediate_size: md_usize(c, "dspark.feed_forward_length")?,
            num_hidden_layers: md_usize(c, "dspark.block_count")?,
            num_attention_heads: md_usize(c, "dspark.attention.head_count")?,
            num_key_value_heads: md_usize(c, "dspark.attention.head_count_kv")?,
            head_dim: md_usize(c, "dspark.attention.key_length")?,
            rms_norm_eps: md_f64(c, "dspark.attention.layer_norm_rms_epsilon")?,
            block_size: md_usize(c, "dspark.dspark.block_size")?,
            mask_token_id: md_u32(c, "dspark.dspark.mask_token_id")?,
            markov_rank: md_usize(c, "dspark.dspark.markov_rank")?,
            target_layer_ids: md_u32_array(c, "dspark.dspark.target_layers")?
                .into_iter()
                .map(|x| x as usize)
                .collect(),
            rope_parameters: DsparkRopeParameters {
                rope_theta: md_f64(c, "dspark.rope.freq_base")?,
            },
            markov_head_type: default_markov_head_type(),
            enable_confidence_head: md_bool(c, "dspark.dspark.confidence_head").unwrap_or(true),
            confidence_head_with_markov: md_bool(c, "dspark.dspark.confidence_head_with_markov")
                .unwrap_or(true),
            log_snr_conditioning: log_snr,
            min_log_snr: if log_snr {
                md_f64(c, "dspark.dspark.min_log_snr")?
            } else {
                default_min_log_snr()
            },
            max_log_snr: if log_snr {
                md_f64(c, "dspark.dspark.max_log_snr")?
            } else {
                default_max_log_snr()
            },
        })
    }
}

/// Standard Qwen3 RMSNorm (weight * x_hat, no zero-centering), routed through
/// the fused Metal kernel (1 dispatch, F32 accumulation inside). The drafter
/// only ever normalizes model-dtype activations, so a single dtype-matched
/// weight suffices.
#[derive(Clone, Debug)]
struct RmsNorm {
    weight: Tensor,
    eps: f64,
}

impl RmsNorm {
    fn load(vb: &VarBuilder, name: &str, size: usize, eps: f64) -> Result<Self> {
        Ok(Self {
            weight: vb.get(size, name)?,
            eps,
        })
    }

    fn forward(&self, xs: &Tensor) -> candle::Result<Tensor> {
        let xs = if xs.is_contiguous() {
            xs.clone()
        } else {
            xs.contiguous()?
        };
        candle_nn::ops::rms_norm(&xs, &self.weight, self.eps as f32)
    }

    /// Fused `(a + b, rms_norm(a + b))` — one dispatch instead of add + norm
    /// (bit-identical; the target model's residual tails use the same
    /// kernel). The drafter has no supported off-Metal/non-BF16 deployment:
    /// anything else is a misconfiguration and fails loudly rather than
    /// silently unfusing.
    fn forward_add(&self, a: &Tensor, b: &Tensor) -> Result<(Tensor, Tensor)> {
        anyhow::ensure!(
            matches!(a.device(), Device::Metal(_))
                && a.dtype() == DType::BF16
                && b.dtype() == DType::BF16,
            "drafter forward_add requires Metal BF16 (got {:?} {:?}/{:?})",
            a.device(),
            a.dtype(),
            b.dtype(),
        );
        crate::fused_norm::fused_rms_norm_add(a, b, &self.weight, self.eps as f32)
    }
}

/// Full-head-dim rotary at the checkpoint's theta. Training's Qwen3 rope path
/// ignores partial_rotary_factor (verified: 128 inv_freq entries for head_dim
/// 256), so the table spans the whole head dimension.
#[derive(Clone, Debug)]
struct Rotary {
    cos: Tensor,
    sin: Tensor,
}

const ROTARY_TABLE_LEN: usize = 16384;

impl Rotary {
    fn new(head_dim: usize, theta: f64, dtype: DType, device: &Device) -> Result<Self> {
        let inv_freq: Vec<f32> = (0..head_dim)
            .step_by(2)
            .map(|i| 1f32 / (theta as f32).powf(i as f32 / head_dim as f32))
            .collect();
        let inv_freq = Tensor::from_vec(inv_freq, (1, head_dim / 2), device)?;
        let t = Tensor::arange(0u32, ROTARY_TABLE_LEN as u32, device)?
            .to_dtype(DType::F32)?
            .reshape((ROTARY_TABLE_LEN, 1))?;
        let freqs = t.matmul(&inv_freq)?;
        // HF convention: emb = cat(freqs, freqs) over the last dim.
        let emb = Tensor::cat(&[&freqs, &freqs], D::Minus1)?;
        Ok(Self {
            cos: emb.cos()?.to_dtype(dtype)?,
            sin: emb.sin()?.to_dtype(dtype)?,
        })
    }

    /// Applies rotation to [b, heads, seq, head_dim] at absolute positions
    /// start..start+seq (HF rotate_half formulation).
    fn apply(&self, xs: &Tensor, start: usize) -> candle::Result<Tensor> {
        let (_, _, seq_len, head_dim) = xs.dims4()?;
        if start + seq_len > ROTARY_TABLE_LEN {
            candle::bail!(
                "rotary table too short: need {} > {ROTARY_TABLE_LEN}",
                start + seq_len
            );
        }
        let cos = self.cos.narrow(0, start, seq_len)?;
        let sin = self.sin.narrow(0, start, seq_len)?;
        let half = head_dim / 2;
        let x1 = xs.narrow(D::Minus1, 0, half)?;
        let x2 = xs.narrow(D::Minus1, half, half)?;
        let rotated = Tensor::cat(&[&x2.neg()?, &x1], D::Minus1)?;
        xs.broadcast_mul(&cos)?
            .add(&rotated.broadcast_mul(&sin)?)
    }
}

#[derive(Clone, Debug)]
struct DraftLayer {
    /// Width-fused [q; k; v] projection: one gemv per layer instead of three
    /// skinny ones — the backbone is dispatch-execution-bound (propose-ladder
    /// 2026-07-14: ~45 tiny dispatches x ~0.15 ms M3 floor).
    qkv_proj: MixedLinear,
    o_proj: MixedLinear,
    q_norm: RmsNorm,
    k_norm: RmsNorm,
    /// Width-fused [gate; up]; the forward applies the fused swiglu kernel.
    gate_up_proj: MixedLinear,
    down_proj: MixedLinear,
    input_layernorm: RmsNorm,
    post_attention_layernorm: RmsNorm,
    // Projected fused-context K/V at their absolute positions (roped), in a
    // grow-on-demand buffer: appends write only the new rows, and propose()
    // appends the block rows then truncates back — no per-round copies of
    // the whole context (the old Tensor::cat pattern was O(T) per round and
    // O(T^2) over a run).
    ctx: TruncatableKvCache,
}

impl DraftLayer {
    fn clear_context(&mut self) {
        self.ctx
            .truncate(0)
            .expect("truncate to zero cannot fail");
    }
}

pub struct DsparkDrafter {
    pub config: DsparkConfig,
    embed_tokens: Tensor,
    layers: Vec<DraftLayer>,
    norm: RmsNorm,
    fc: Linear,
    hidden_norm: RmsNorm,
    lm_head: MixedLinear,
    markov_w1: Tensor,
    markov_w2: MixedLinear,
    confidence: Linear,
    // Precomputed GIDD log-SNR conditioning bias [block_size, hidden], added to
    // the draft-block embedding each propose. None when the drafter has no
    // log-SNR conditioning. It's a fixed function of block_size/min/max_log_snr
    // and the fc1/fc2 weights, so it's evaluated once at load.
    log_snr_bias: Option<Tensor>,
    rotary: Rotary,
    // FR-Spec draft-vocabulary restriction: when set, lm_head and markov_w2
    // hold only these rows (rank order), and proposal argmaxes remap through
    // this id table. Committed output is unaffected (verification is exact);
    // only draft cost and tau move.
    draft_vocab_ids: Option<Tensor>,
    // Single-dispatch chain scratch: [block_size] interleaved (packed-max,
    // counter) u32 pairs, zeroed at allocation and self-cleaned by the
    // kernel (fork dspark.metal documents the protocol). Lazily allocated on
    // the first eligible propose; held for the drafter's lifetime so the
    // pool never recycles it.
    markov_fused_slots: std::sync::OnceLock<std::sync::Arc<candle_metal_kernels::metal::Buffer>>,
    device: Device,
    dtype: DType,
    /// Per-segment fenced propose timing (diagnostics); resolved at the
    /// command entry and injected at load — the module reads no env.
    propose_timing: bool,
}

#[derive(Clone, Debug)]
pub struct DraftProposal {
    pub tokens: Vec<u32>,
    pub confidence_logits: Vec<f32>,
    /// Alternate chain branching at position 0 from the runner-up Markov
    /// token — nearly free by construction (base_logits\[k\] is branch-
    /// independent; only the Markov bias chains), for tree speculation.
    pub alt_tokens: Vec<u32>,
    pub alt_confidence_logits: Vec<f32>,
    /// Populated only by `propose_with_diagnostics` (parity harness); the
    /// hot loop skips materializing them (~0.2 ms/round of vocab-wide cats).
    pub block_hidden: Option<Tensor>,
    pub base_logits: Option<Tensor>,
    pub corrected_logits: Option<Tensor>,
}

fn maybe_slice_rows(weight: Tensor, ids: Option<&[u32]>) -> Result<Tensor> {
    match ids {
        None => Ok(weight),
        Some(ids) => {
            let idx = Tensor::from_slice(ids, ids.len(), weight.device())?;
            Ok(weight.index_select(&idx, 0)?.contiguous()?)
        }
    }
}

fn quantize_or_dense(
    weight: Tensor,
    dtype: Option<candle::quantized::GgmlDType>,
    device: &Device,
    ctx: &crate::model_ctx::ModelCtx,
) -> Result<MixedLinear> {
    match dtype {
        None => Ok(MixedLinear::dense(Linear::new(weight, None))),
        Some(ggml) => {
            let cpu_f32 = weight
                .to_dtype(DType::F32)?
                .to_device(&Device::Cpu)?;
            let q = candle::quantized::QTensor::quantize_onto(&cpu_f32, ggml, device)?;
            Ok(ctx.quantized_linear(q)?)
        }
    }
}

/// Read a GGUF tensor by name, dequantize to `dtype`. candle reverses gguf
/// `ne`, so quantized weights come back `[out, in]` — the port's convention.
fn read_dense(gguf: &crate::gguf::GgufFile, name: &str, device: &Device, dtype: DType) -> Result<Tensor> {
    Ok(gguf.read_qtensor(name, device)?.dequantize(device)?.to_dtype(dtype)?)
}

/// Precompute the GIDD log-SNR conditioning bias [block, hidden] (src/models/
/// dspark.cpp in the prism llama.cpp fork). Each block's anchor row (pos 0)
/// takes max_log_snr, the masked rows min_log_snr; a 128-dim sinusoidal embed
/// (t scaled by 1000) runs through fc1 -> silu -> fc2. Purely a function of the
/// block/bounds/weights, so it's evaluated once and added every propose.
fn compute_log_snr_bias(
    block: usize,
    min_snr: f64,
    max_snr: f64,
    fc1: &Linear,
    fc2: &Linear,
    device: &Device,
    dtype: DType,
) -> Result<Tensor> {
    const N_FREQ: usize = 128;
    const HALF: usize = N_FREQ / 2;
    if !(max_snr > min_snr) || !min_snr.is_finite() || !max_snr.is_finite() {
        anyhow::bail!("log-SNR conditioning: need finite max ({max_snr}) > min ({min_snr})");
    }
    let mut feat = vec![0f32; block * N_FREQ];
    for pos in 0..block {
        let log_snr = if pos % block == 0 { max_snr } else { min_snr };
        let t = ((log_snr - min_snr) / (max_snr - min_snr) * 1000.0) as f32;
        for i in 0..HALF {
            let freq = (-(10000f32.ln()) * (i as f32) / (HALF as f32)).exp();
            let angle = t * freq;
            feat[pos * N_FREQ + i] = angle.sin();
            feat[pos * N_FREQ + HALF + i] = angle.cos();
        }
    }
    let feat = Tensor::from_vec(feat, (block, N_FREQ), device)?.to_dtype(dtype)?;
    let h = candle_nn::ops::silu(&fc1.forward(&feat)?)?;
    Ok(fc2.forward(&h)?)
}

/// Load request for [`DsparkDrafter::load`] — a parameter object so the
/// loader has one named, evolvable argument instead of a positional list.
///
/// - `quantize_heads` post-hoc quantizes the two 248k-vocab weight reads
///   (lm_head, markov_w2) at load — no artifact, no retraining. markov_w1
///   stays BF16 (index_select gather) and the confidence head stays dense.
///   The risk surface is tau, not correctness: drafts are target-verified.
/// - `draft_vocab`: FR-Spec top-k token ids (rank order). The vocab-wide
///   draft heads are sliced to these rows before any quantization; markov_w1,
///   the embedding and the confidence head keep the full vocabulary.
/// - `propose_timing`: the spec-run per-segment attribution diagnostic
///   (entrypoint-resolved); off for non-spec-run entrypoints.
pub struct DsparkDrafterRequest<'a> {
    pub dir: &'a Path,
    pub device: &'a Device,
    pub dtype: DType,
    pub quantize_heads: Option<candle::quantized::GgmlDType>,
    pub draft_vocab: Option<&'a [u32]>,
    pub propose_timing: bool,
}

impl<'a> DsparkDrafterRequest<'a> {
    /// The minimal request: no head quantization, full vocab, no timing.
    pub fn new(dir: &'a Path, device: &'a Device, dtype: DType) -> Self {
        Self {
            dir,
            device,
            dtype,
            quantize_heads: None,
            draft_vocab: None,
            propose_timing: false,
        }
    }
}

impl DsparkDrafter {
    pub fn load(req: DsparkDrafterRequest, ctx: &crate::model_ctx::ModelCtx) -> Result<Self> {
        let DsparkDrafterRequest {
            dir,
            device,
            dtype,
            quantize_heads,
            draft_vocab,
            propose_timing,
        } = req;
        let config = DsparkConfig::from_dir(dir)?;
        if config.markov_head_type != "vanilla"
            || !config.enable_confidence_head
            || !config.confidence_head_with_markov
        {
            anyhow::bail!(
                "drafter checkpoint wants markov_head_type={:?} \
                 enable_confidence_head={} confidence_head_with_markov={}; this \
                 port implements only vanilla + markov-feature confidence",
                config.markov_head_type,
                config.enable_confidence_head,
                config.confidence_head_with_markov,
            );
        }
        let weights = dir.join("model.safetensors");
        let vb = unsafe {
            VarBuilder::from_mmaped_safetensors(std::slice::from_ref(&weights), dtype, device)
                .with_context(|| format!("mmap drafter weights {}", weights.display()))?
        };
        let h = config.hidden_size;
        let heads = config.num_attention_heads;
        let kv_heads = config.num_key_value_heads;
        let head_dim = config.head_dim;
        let eps = config.rms_norm_eps;

        let mut layers = Vec::with_capacity(config.num_hidden_layers);
        for i in 0..config.num_hidden_layers {
            let p = format!("layers.{i}");
            // Width-fuse [q;k;v] and [gate;up] at load: row-concatenation of
            // [out, in] weights is exact (no quantization here — dense bf16).
            let qkv = Tensor::cat(
                &[
                    &vb.get((heads * head_dim, h), &format!("{p}.self_attn.q_proj.weight"))?,
                    &vb.get((kv_heads * head_dim, h), &format!("{p}.self_attn.k_proj.weight"))?,
                    &vb.get((kv_heads * head_dim, h), &format!("{p}.self_attn.v_proj.weight"))?,
                ],
                0,
            )?;
            let gate_up = Tensor::cat(
                &[
                    &vb.get((config.intermediate_size, h), &format!("{p}.mlp.gate_proj.weight"))?,
                    &vb.get((config.intermediate_size, h), &format!("{p}.mlp.up_proj.weight"))?,
                ],
                0,
            )?;
            layers.push(DraftLayer {
                qkv_proj: MixedLinear::dense(Linear::new(qkv, None)),
                o_proj: MixedLinear::dense(Linear::new(
                    vb.get((h, heads * head_dim), &format!("{p}.self_attn.o_proj.weight"))?,
                    None,
                )),
                q_norm: RmsNorm::load(&vb, &format!("{p}.self_attn.q_norm.weight"), head_dim, eps)?,
                k_norm: RmsNorm::load(&vb, &format!("{p}.self_attn.k_norm.weight"), head_dim, eps)?,
                gate_up_proj: MixedLinear::dense(Linear::new(gate_up, None)),
                down_proj: MixedLinear::dense(Linear::new(
                    vb.get((h, config.intermediate_size), &format!("{p}.mlp.down_proj.weight"))?,
                    None,
                )),
                input_layernorm: RmsNorm::load(&vb, &format!("{p}.input_layernorm.weight"), h, eps)?,
                post_attention_layernorm: RmsNorm::load(&vb, &format!("{p}.post_attention_layernorm.weight"), h, eps)?,
                ctx: TruncatableKvCache::new(),
            });
        }

        Ok(Self {
            embed_tokens: vb.get((config.vocab_size, h), "embed_tokens.weight")?,
            norm: RmsNorm::load(&vb, "norm.weight", h, eps)?,
            fc: Linear::new(
                vb.get((h, config.target_layer_ids.len() * h), "fc.weight")?,
                None,
            ),
            hidden_norm: RmsNorm::load(&vb, "hidden_norm.weight", h, eps)?,
            lm_head: quantize_or_dense(
                maybe_slice_rows(
                    vb.get((config.vocab_size, h), "lm_head.weight")?,
                    draft_vocab,
                )?,
                quantize_heads,
                device,
                ctx,
            )?,
            markov_w1: vb.get((config.vocab_size, config.markov_rank), "markov_head.markov_w1.weight")?,
            markov_w2: quantize_or_dense(
                maybe_slice_rows(
                    vb.get((config.vocab_size, config.markov_rank), "markov_head.markov_w2.weight")?,
                    draft_vocab,
                )?,
                quantize_heads,
                device,
                ctx,
            )?,
            draft_vocab_ids: draft_vocab
                .map(|ids| Tensor::from_slice(ids, ids.len(), device))
                .transpose()?,
            confidence: Linear::new(
                vb.get((1, h + config.markov_rank), "confidence_head.proj.weight")?,
                Some(vb.get(1, "confidence_head.proj.bias")?),
            ),
            // The safetensors round-4 drafter has no log-SNR conditioning; the
            // GGUF loader path populates this when the metadata enables it.
            log_snr_bias: None,
            rotary: Rotary::new(head_dim, config.rope_parameters.rope_theta, dtype, device)?,
            layers,
            markov_fused_slots: std::sync::OnceLock::new(),
            device: device.clone(),
            dtype,
            propose_timing,
            config,
        })
    }

    /// Load the shipped Bonsai DSpark drafter from its GGUF. Backbone + heads
    /// dequantize to `dtype` (dense); the log-SNR conditioning bias is
    /// precomputed. FR-Spec draft-vocab slicing is not yet supported here.
    pub fn load_gguf(
        gguf: &crate::gguf::GgufFile,
        device: &Device,
        dtype: DType,
        ctx: &crate::model_ctx::ModelCtx,
        propose_timing: bool,
    ) -> Result<Self> {
        let config = DsparkConfig::from_gguf(gguf)?;
        let h = config.hidden_size;
        let heads = config.num_attention_heads;
        let kv_heads = config.num_key_value_heads;
        let head_dim = config.head_dim;
        let eps = config.rms_norm_eps;
        let rd = |name: &str| read_dense(gguf, name, device, dtype);
        // Keep backbone projections + the 248k-row lm_head PACKED (never expand
        // to dense bf16) so the drafter fits in memory alongside the target.
        // `single` wraps one quantized weight; `fuse` byte-cats packed blocks
        // along output rows (bit-exact — Q4_1 blocks run along the input dim,
        // so a row-cat never splits a block).
        let single = |name: &str| -> Result<MixedLinear> {
            Ok(ctx.quantized_linear(gguf.read_qtensor(name, device)?)?)
        };
        let fuse = |names: &[String], out_total: usize, in_dim: usize| -> Result<MixedLinear> {
            use candle::quantized::ggml_file::qtensor_from_ggml;
            let qts = names
                .iter()
                .map(|n| gguf.read_qtensor(n, device))
                .collect::<candle::Result<Vec<_>>>()?;
            let qdtype = qts[0].dtype();
            let mut bytes = Vec::new();
            for qt in &qts {
                anyhow::ensure!(qt.dtype() == qdtype, "fused drafter parts differ in ggml dtype");
                bytes.extend_from_slice(&qt.data()?);
            }
            let fused = qtensor_from_ggml(qdtype, &bytes, vec![out_total, in_dim], device)?;
            Ok(ctx.quantized_linear(fused)?)
        };
        let lm_head = single("output.weight")?;
        let norm = |name: &str| -> Result<RmsNorm> {
            Ok(RmsNorm { weight: rd(name)?, eps })
        };

        let qkv_out = (heads + 2 * kv_heads) * head_dim;
        let gate_up_out = 2 * config.intermediate_size;
        let mut layers = Vec::with_capacity(config.num_hidden_layers);
        for i in 0..config.num_hidden_layers {
            let p = format!("blk.{i}");
            layers.push(DraftLayer {
                qkv_proj: fuse(
                    &[
                        format!("{p}.attn_q.weight"),
                        format!("{p}.attn_k.weight"),
                        format!("{p}.attn_v.weight"),
                    ],
                    qkv_out,
                    h,
                )?,
                o_proj: single(&format!("{p}.attn_output.weight"))?,
                q_norm: norm(&format!("{p}.attn_q_norm.weight"))?,
                k_norm: norm(&format!("{p}.attn_k_norm.weight"))?,
                gate_up_proj: fuse(
                    &[format!("{p}.ffn_gate.weight"), format!("{p}.ffn_up.weight")],
                    gate_up_out,
                    h,
                )?,
                down_proj: single(&format!("{p}.ffn_down.weight"))?,
                input_layernorm: norm(&format!("{p}.attn_norm.weight"))?,
                post_attention_layernorm: norm(&format!("{p}.ffn_norm.weight"))?,
                ctx: TruncatableKvCache::new(),
            });
        }

        let log_snr_bias = if config.log_snr_conditioning {
            let fc1 = Linear::new(
                rd("dspark.log_snr_fc1.weight")?,
                Some(rd("dspark.log_snr_fc1.bias")?),
            );
            let fc2 = Linear::new(
                rd("dspark.log_snr_fc2.weight")?,
                Some(rd("dspark.log_snr_fc2.bias")?),
            );
            Some(compute_log_snr_bias(
                config.block_size,
                config.min_log_snr,
                config.max_log_snr,
                &fc1,
                &fc2,
                device,
                dtype,
            )?)
        } else {
            None
        };

        Ok(Self {
            embed_tokens: rd("token_embd.weight")?,
            norm: norm("output_norm.weight")?,
            fc: Linear::new(rd("dspark.fc.weight")?, None),
            hidden_norm: norm("dspark.hidden_norm.weight")?,
            lm_head,
            markov_w1: rd("dspark.markov_head_a.weight")?,
            markov_w2: MixedLinear::dense(Linear::new(rd("dspark.markov_head_b.weight")?, None)),
            draft_vocab_ids: None,
            confidence: Linear::new(
                rd("dspark.confidence_head.weight")?,
                Some(rd("dspark.confidence_head.bias")?),
            ),
            log_snr_bias,
            rotary: Rotary::new(head_dim, config.rope_parameters.rope_theta, dtype, device)?,
            layers,
            markov_fused_slots: std::sync::OnceLock::new(),
            device: device.clone(),
            dtype,
            propose_timing,
            config,
        })
    }

    pub fn clear_context(&mut self) {
        for layer in &mut self.layers {
            layer.clear_context();
        }
    }

    fn embed(&self, ids: &[u32]) -> candle::Result<Tensor> {
        let ids = Tensor::from_slice(ids, ids.len(), &self.device)?;
        self.embed_tokens.index_select(&ids, 0)?.unsqueeze(0)
    }

    /// Fuses raw capture-layer concat states ([1, m, capture*hidden]) and
    /// appends per-layer projected K/V at absolute positions
    /// start_pos..start_pos+m.
    pub fn append_context(&mut self, raw_ctx: &Tensor, start_pos: usize) -> Result<()> {
        let raw_ctx = raw_ctx.to_dtype(self.dtype)?;
        let fused = self.hidden_norm.forward(&self.fc.forward(&raw_ctx)?)?;
        let (b, m, _) = fused.dims3()?;
        let heads = self.config.num_attention_heads;
        let kv_heads = self.config.num_key_value_heads;
        let head_dim = self.config.head_dim;
        for layer in &mut self.layers {
            // Context rows only need K/V, but the projection is width-fused:
            // one qkv gemv with the Q head group discarded is still one
            // dispatch fewer than two split gemvs, and per-row gemv results
            // are independent, so the K/V bits are unchanged.
            let qkv = layer
                .qkv_proj
                .forward(&fused)?
                .reshape((b, m, heads + 2 * kv_heads, head_dim))?;
            let k = layer
                .k_norm
                .forward(&qkv.narrow(2, heads, kv_heads)?.transpose(1, 2)?.contiguous()?)?;
            let k = self.rotary.apply(&k, start_pos)?;
            let v_new = qkv
                .narrow(2, heads + kv_heads, kv_heads)?
                .transpose(1, 2)?
                .contiguous()?;
            if layer.ctx.len() != start_pos {
                anyhow::bail!(
                    "drafter context length {} does not match append position {start_pos}",
                    layer.ctx.len()
                );
            }
            layer.ctx.append(&k.contiguous()?, &v_new)?;
        }
        Ok(())
    }

    /// One draft block at absolute positions anchor_pos..anchor_pos+block_size,
    /// attending bidirectionally over cached context + the block. The backbone
    /// ALWAYS runs on the full block_size positions — training only ever saw
    /// full blocks, and bidirectional attention makes every h_k depend on the
    /// trailing mask tokens, so a shortened block is out-of-distribution.
    /// Only the first `gamma` positions go through lm_head/Markov/confidence.
    pub fn propose(&mut self, anchor_token: u32, anchor_pos: usize, gamma: usize) -> Result<DraftProposal> {
        self.propose_inner(anchor_token, anchor_pos, gamma, false, false)
    }

    /// Also drafts the alternate chain branching at position 0 (runner-up
    /// Markov token) for tree speculation: ~1 extra Markov gemv per position.
    pub fn propose_branching(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
    ) -> Result<DraftProposal> {
        self.propose_inner(anchor_token, anchor_pos, gamma, false, true)
    }

    /// Parity-harness variant that also materializes block_hidden /
    /// base_logits / corrected_logits.
    pub fn propose_with_diagnostics(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
    ) -> Result<DraftProposal> {
        self.propose_inner(anchor_token, anchor_pos, gamma, true, false)
    }

    /// Device-side stage of a proposal: backbone forward + Markov chains,
    /// returning un-materialized tensors. No host readback happens here —
    /// callers choose between the synchronous pack+read (propose_inner) and
    /// the deferred-drain form (propose_device).
    fn propose_tensors(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
        branch: bool,
        force_ops: bool,
    ) -> Result<ProposalTensors> {
        // Drain in-flight work (async-readback verify chunks overlap propose)
        // before arming the first timer, or its fence absorbs the previous
        // round's tail and inflates the backbone bucket — the 6.7-vs-10.1ms
        // bimodality of the 2026-07-13 cpb-ladder was exactly this.
        if self.propose_timing {
            self.device.synchronize()?;
        }
        let ladder_start = self.propose_timing.then(std::time::Instant::now);
        let backbone = self.propose_backbone(anchor_token, anchor_pos, gamma)?;
        let backbone_ms = ladder_start
            .map(|t0| -> Result<f64> {
                self.device.synchronize()?;
                Ok(t0.elapsed().as_secs_f64() * 1e3)
            })
            .transpose()?;
        // Branch (tree) rounds and diagnostics consume the corrected step
        // logits, which only the ops chain materializes; everything else
        // takes the fused kernel — an unsupported device/dtype/w2 layout is a
        // misconfiguration and errors inside it rather than degrading.
        let chain_start = self.propose_timing.then(std::time::Instant::now);
        let out = if !branch && !force_ops {
            self.markov_chain_fused(anchor_token, gamma, &backbone)?
        } else {
            self.markov_chain_ops(anchor_token, gamma, branch, backbone)?
        };
        if let (Some(t0), Some(bb)) = (chain_start, backbone_ms) {
            self.device.synchronize()?;
            let chain_ms = t0.elapsed().as_secs_f64() * 1e3;
            eprintln!("propose-ladder gamma={gamma}: backbone+heads {bb:.3} ms, chain {chain_ms:.3} ms");
        }
        Ok(out)
    }

    /// Backbone forward + heads: (block_hidden [1, gamma, h], base_logits
    /// [1, gamma, draft_vocab]).
    fn propose_backbone(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
    ) -> Result<(Tensor, Tensor)> {
        let block = self.config.block_size;
        if gamma == 0 || gamma > block {
            anyhow::bail!("gamma {gamma} outside 1..={block}");
        }
        let mut ids = vec![self.config.mask_token_id; block];
        ids[0] = anchor_token;
        let mut hidden = self.embed(&ids)?;
        // GIDD log-SNR conditioning: add the fixed per-position bias to the
        // draft-block embedding before the layers (anchor row = max-SNR embed,
        // masked rows = min-SNR embed). Bias is [block, hidden]; hidden is
        // [1, block, hidden].
        if let Some(bias) = &self.log_snr_bias {
            hidden = hidden.broadcast_add(&bias.unsqueeze(0)?)?;
        }
        let (b, q_len, _) = hidden.dims3()?;
        let heads = self.config.num_attention_heads;
        let kv_heads = self.config.num_key_value_heads;
        let head_dim = self.config.head_dim;
        let scale = 1.0 / (head_dim as f64).sqrt();

        // Cross-layer fused add+norm needs the NEXT layer's input norm while
        // the current layer is mutably borrowed; norm handles are Arc-cheap.
        let input_norms: Vec<RmsNorm> = self
            .layers
            .iter()
            .map(|l| l.input_layernorm.clone())
            .collect();
        let n_layers = self.layers.len();
        let mut normed = input_norms[0].forward(&hidden)?;
        for i in 0..n_layers {
            let layer = &mut self.layers[i];
            // One fused [q;k;v] gemv; the contiguous reshape to head groups
            // is free, and each head-group slice pays exactly the same
            // transpose+contiguous copy the split projections paid. QK-norm
            // runs after the transpose (it reduces over head_dim, which
            // transpose does not touch — bit-identical, and it saves the
            // strided-input copy the norm would otherwise make).
            let qkv = layer
                .qkv_proj
                .forward(&normed)?
                .reshape((b, q_len, heads + 2 * kv_heads, head_dim))?;
            let q = layer
                .q_norm
                .forward(&qkv.narrow(2, 0, heads)?.transpose(1, 2)?.contiguous()?)?;
            let q = self.rotary.apply(&q, anchor_pos)?;
            let k_new = layer
                .k_norm
                .forward(&qkv.narrow(2, heads, kv_heads)?.transpose(1, 2)?.contiguous()?)?;
            let k_new = self.rotary.apply(&k_new, anchor_pos)?;
            let v_new = qkv
                .narrow(2, heads + kv_heads, kv_heads)?
                .transpose(1, 2)?
                .contiguous()?;
            // Block rows are appended into the context buffer for the
            // attention call and truncated straight back out: bidirectional
            // attention over [ctx | block] with zero copies of the context.
            // The fused SDPA kernel handles GQA natively (no repeat_kv).
            let prev_len = layer.ctx.len();
            let (k_all, v_all) = layer
                .ctx
                .append(&k_new.contiguous()?, &v_new)?;
            let out = candle_nn::ops::sdpa(
                &q.contiguous()?,
                &k_all,
                &v_all,
                None,
                false,
                scale as f32,
                1.0,
            )?;
            layer.ctx.truncate(prev_len)?;
            let out = out
                .transpose(1, 2)?
                .reshape((b, q_len, heads * head_dim))?;
            let attn = layer.o_proj.forward(&out)?;
            // Fused residual + post-attention norm (2 dispatches -> 1).
            let (h_attn, post_normed) =
                layer.post_attention_layernorm.forward_add(&hidden, &attn)?;
            // Fused [gate;up] gemv + the fused swiglu kernel (5 -> 3).
            let gate_up = layer.gate_up_proj.forward(&post_normed)?;
            let gated = candle_nn::ops::swiglu(&gate_up)?;
            let down = layer.down_proj.forward(&gated)?;
            // Fused MLP residual + the NEXT norm — the following layer's
            // input norm, or the model's final norm on the last layer.
            let next_norm = if i + 1 < n_layers {
                &input_norms[i + 1]
            } else {
                &self.norm
            };
            let (h_next, n_next) = next_norm.forward_add(&h_attn, &down)?;
            hidden = h_next;
            normed = n_next;
        }
        // `normed` is final_norm(hidden) via the last fused tail. Heads read
        // only the proposal prefix; narrowing before lm_head skips the vocab
        // projection for the unused trailing block positions.
        let block_hidden = normed.narrow(1, 0, gamma)?;
        let base_logits = self.lm_head.forward(&block_hidden.contiguous()?)?;
        Ok((block_hidden, base_logits))
    }

    /// Per-step tensor-ops chain: the only implementation that materializes
    /// the corrected step logits (branch/tree and diagnostics consume them)
    /// and the only one that runs off-Metal. The hot path uses the fused
    /// kernel instead (markov_chain_fused).
    fn markov_chain_ops(
        &self,
        anchor_token: u32,
        gamma: usize,
        branch: bool,
        (block_hidden, base_logits): (Tensor, Tensor),
    ) -> Result<ProposalTensors> {
        // Left-to-right greedy Markov sampling; corrected logits define p_d.
        // The token chain stays on device (argmax feeds the next index_select
        // directly) so the loop enqueues without host syncs; tokens and
        // confidences are read back once at the end.
        let mut prev_id = Tensor::from_slice(&[anchor_token], 1, &self.device)?;
        let mut token_tensors = Vec::with_capacity(gamma);
        let mut corrected = Vec::with_capacity(gamma);
        let mut features = Vec::with_capacity(gamma);
        let mut sub_argmax0: Option<Tensor> = None;
        for k in 0..gamma {
            let prev_emb = self.markov_w1.index_select(&prev_id, 0)?;
            let bias = self.markov_w2.forward(&prev_emb)?;
            let step = (base_logits.i((0, k))?.unsqueeze(0)? + &bias)?;
            let sub_token = step.to_dtype(DType::F32)?.argmax(D::Minus1)?;
            // Draft-vocab argmaxes index the sliced rows; remap to global ids
            // (one device-side gather) so the Markov chain and readback stay
            // in real token space.
            let token = match &self.draft_vocab_ids {
                Some(ids) => ids.index_select(&sub_token, 0)?,
                None => sub_token.clone(),
            };
            if k == 0 {
                sub_argmax0 = Some(sub_token);
            }
            let h_k = block_hidden.i((0, k))?.unsqueeze(0)?;
            features.push(Tensor::cat(&[&h_k, &prev_emb.to_dtype(self.dtype)?], D::Minus1)?);
            corrected.push(step);
            token_tensors.push(token.clone());
            prev_id = token;
        }
        // Alternate chain: branch at position 0 from the runner-up Markov
        // token; base_logits rows are branch-independent, so this is one
        // masked-argmax plus gamma-1 extra Markov steps.
        let mut alt_token_tensors = Vec::new();
        let mut alt_features = Vec::new();
        if branch && gamma > 0 {
            let step0 = corrected[0].to_dtype(DType::F32)?.squeeze(0)?;
            let neg = Tensor::full(-1e30f32, 1, &self.device)?;
            // Keep the id rank-1 like the main chain's argmax(Minus1) output:
            // markov_w1.index_select rejects rank-0 indices. The mask index
            // lives in the (possibly sliced) logit space; the winner remaps
            // to a global id afterwards.
            let mask_idx = sub_argmax0
                .as_ref()
                .expect("main chain populated position 0")
                .clone();
            let second_sub = step0
                .index_add(&mask_idx, &neg, 0)?
                .argmax(0)?
                .unsqueeze(0)?;
            let second = match &self.draft_vocab_ids {
                Some(ids) => ids.index_select(&second_sub, 0)?,
                None => second_sub,
            };
            let mut prev = second.clone();
            alt_token_tensors.push(second);
            for k in 0..gamma {
                let prev_emb = self.markov_w1.index_select(&prev, 0)?;
                let h_k = block_hidden.i((0, k))?.unsqueeze(0)?;
                alt_features
                    .push(Tensor::cat(&[&h_k, &prev_emb.to_dtype(self.dtype)?], D::Minus1)?);
                if k + 1 < gamma {
                    let bias = self.markov_w2.forward(&prev_emb)?;
                    let step = (base_logits.i((0, k + 1))?.unsqueeze(0)? + &bias)?;
                    let sub = step.to_dtype(DType::F32)?.argmax(D::Minus1)?;
                    let token = match &self.draft_vocab_ids {
                        Some(ids) => ids.index_select(&sub, 0)?,
                        None => sub,
                    };
                    alt_token_tensors.push(token.clone());
                    prev = token;
                }
            }
        }

        Ok(ProposalTensors {
            token_tensors,
            alt_token_tensors,
            features,
            alt_features,
            corrected,
            block_hidden,
            base_logits,
        })
    }

    /// Fused Metal chain: two dispatches per step (fork dspark.metal)
    /// replacing the ~5-6 tiny serialized ops per step — 78us/step vs
    /// ~1170us/step measured on the M3. The drafter's only supported
    /// deployment is Metal BF16 with a q8_0 or dense-bf16 Markov head;
    /// anything else fails loudly here.
    fn markov_chain_fused(
        &self,
        anchor_token: u32,
        gamma: usize,
        (block_hidden, base_logits): &(Tensor, Tensor),
    ) -> Result<ProposalTensors> {
        let Device::Metal(metal_dev) = &self.device else {
            anyhow::bail!("fused markov chain requires a Metal device");
        };
        let r = self.config.markov_rank;
        anyhow::ensure!(
            self.dtype == DType::BF16
                && base_logits.dtype() == DType::BF16
                && self.markov_w1.dtype() == DType::BF16,
            "fused markov chain requires BF16 (dtype {:?}, base {:?}, w1 {:?})",
            self.dtype,
            base_logits.dtype(),
            self.markov_w1.dtype(),
        );
        anyhow::ensure!(
            r <= candle_metal_kernels::MARKOV_TPG && r.is_multiple_of(32),
            "fused markov chain requires rank %32==0 and <= {} (got {r})",
            candle_metal_kernels::MARKOV_TPG,
        );
        // w2: q8_0 ggml blocks or a dense bf16 row matrix.
        let (w2_buf, w2_off, w2_q8, vd) = if let Some(q) = self.markov_w2.qtensor() {
            anyhow::ensure!(
                q.dtype() == GgmlDType::Q8_0,
                "fused markov chain supports q8_0 or dense bf16 markov_w2; got {:?} \
                 (use --drafter-quantize q8-0 or run unquantized)",
                q.dtype(),
            );
            let QStorage::Metal(ms) = q.storage() else {
                anyhow::bail!("markov_w2 qtensor is not Metal-resident");
            };
            (ms.buffer().clone(), 0usize, true, q.shape().dims()[0])
        } else if let Some(w) = self.markov_w2.dense_weight() {
            anyhow::ensure!(
                w.dtype() == DType::BF16 && w.dims().len() == 2,
                "dense markov_w2 must be BF16 [vd, rank]; got {:?} {:?}",
                w.dtype(),
                w.dims(),
            );
            let (st, ly) = w.storage_and_layout();
            let Storage::Metal(ms) = &*st else {
                anyhow::bail!("dense markov_w2 is not Metal-resident");
            };
            (
                ms.buffer().clone(),
                ly.start_offset() * 2,
                false,
                w.dims()[0],
            )
        } else {
            anyhow::bail!("markov_w2 has neither a qtensor nor a dense weight");
        };
        anyhow::ensure!(
            base_logits.dims() == [1, gamma, vd],
            "markov base_logits {:?} does not match draft vocab {vd}",
            base_logits.dims()
        );
        // Draft->global remap table when FR-Spec restricts the head.
        let (ids_buf, ids_off, remap) = match &self.draft_vocab_ids {
            Some(ids) => {
                anyhow::ensure!(
                    ids.dtype() == DType::U32,
                    "draft_vocab_ids must be U32; got {:?}",
                    ids.dtype(),
                );
                let (st, ly) = ids.storage_and_layout();
                let Storage::Metal(ms) = &*st else {
                    anyhow::bail!("draft_vocab_ids is not Metal-resident");
                };
                (
                    Some(ms.buffer().clone()),
                    ly.start_offset() * 4,
                    true,
                )
            }
            None => (None, 0usize, false),
        };

        let base_contig = base_logits.contiguous()?;
        // Clone the Arc-backed buffer handles inside scopes so the storage
        // read guards drop before dispatch (and before base_contig moves
        // into the returned ProposalTensors).
        let (base_buf, base_off) = {
            let (st, ly) = base_contig.storage_and_layout();
            let Storage::Metal(ms) = &*st else {
                anyhow::bail!("base_logits is not Metal-resident");
            };
            (ms.buffer().clone(), ly.start_offset() * 2)
        };
        let (w1_buf, w1_off) = {
            let (st, ly) = self.markov_w1.storage_and_layout();
            let Storage::Metal(ms) = &*st else {
                anyhow::bail!("markov_w1 is not Metal-resident");
            };
            (ms.buffer().clone(), ly.start_offset() * 2)
        };

        let mut chain_init = vec![0u32; gamma + 1];
        chain_init[0] = anchor_token;
        let chain = metal_dev
            .new_buffer_builder()
            .with_data(&chain_init)
            .with_label("markov_chain")
            .build()?;
        let partials = metal_dev
            .new_buffer_builder()
            .with_size(candle_metal_kernels::MARKOV_NTG * 8)
            .with_label("markov_partials")
            .build()?;
        let tokens_buf = metal_dev
            .new_buffer_builder()
            .with_size(gamma * 4)
            .with_label("markov_tokens")
            .build()?;
        let prev_embs_buf = metal_dev
            .new_buffer_builder()
            .with_size(gamma * r * 2)
            .with_label("markov_prev_embs")
            .build()?;
        // Single-dispatch steps whenever the packed atomic key can carry the
        // vocabulary index; the two-dispatch shape covers larger vocabs.
        let fused_slots = if vd <= candle_metal_kernels::MARKOV_FUSED_MAX_VD {
            if self.markov_fused_slots.get().is_none() {
                let slots = metal_dev
                    .new_buffer_builder()
                    .with_zeros(self.config.block_size.max(gamma) * 8)
                    .with_label("markov_fused_slots")
                    .build()?;
                let _ = self.markov_fused_slots.set(slots);
            }
            self.markov_fused_slots.get()
        } else {
            None
        };

        {
            let encoder = metal_dev.command_encoder()?;
            candle_metal_kernels::call_markov_chain(
                metal_dev.metal_device(),
                &encoder,
                metal_dev.kernels(),
                candle_metal_kernels::MarkovChainArgs {
                    gamma,
                    draft_vocab: vd,
                    rank: r,
                    w2_q8,
                    w1: (&w1_buf, w1_off),
                    w2: (&w2_buf, w2_off),
                    base: (&base_buf, base_off),
                    chain: &chain,
                    partials: &partials,
                    ids: (
                        ids_buf.as_ref().unwrap_or(&*tokens_buf),
                        ids_off,
                    ),
                    remap,
                    tokens: &tokens_buf,
                    prev_embs: &prev_embs_buf,
                    fused_scratch: fused_slots.map(|b| &**b),
                },
            )
            .map_err(|e| anyhow::anyhow!("markov chain dispatch: {e}"))?;
        }

        let tokens_t = Tensor::from_storage(
            Storage::Metal(MetalStorage::new(
                tokens_buf,
                metal_dev.clone(),
                gamma,
                DType::U32,
            )),
            (gamma,),
            BackpropOp::none(),
            false,
        );
        let prev_embs_t = Tensor::from_storage(
            Storage::Metal(MetalStorage::new(
                prev_embs_buf,
                metal_dev.clone(),
                gamma * r,
                DType::BF16,
            )),
            (gamma, r),
            BackpropOp::none(),
            false,
        );

        let mut token_tensors = Vec::with_capacity(gamma);
        let mut features = Vec::with_capacity(gamma);
        for k in 0..gamma {
            token_tensors.push(tokens_t.narrow(0, k, 1)?);
            let h_k = block_hidden.i((0, k))?.unsqueeze(0)?;
            features.push(Tensor::cat(
                &[&h_k, &prev_embs_t.narrow(0, k, 1)?],
                D::Minus1,
            )?);
        }
        Ok(ProposalTensors {
            token_tensors,
            alt_token_tensors: Vec::new(),
            features,
            alt_features: Vec::new(),
            corrected: Vec::new(),
            block_hidden: block_hidden.clone(),
            base_logits: base_contig,
        })
    }

    /// Device-side [confidences (main then alt) | token ids as f32] pack —
    /// the single buffer a proposal readback drains (u32 < 2^24 is exact in
    /// f32, so ids ride the confidence buffer).
    fn pack_proposal(&self, t: &ProposalTensors) -> Result<Tensor> {
        let feature_refs = t
            .features
            .iter()
            .chain(t.alt_features.iter())
            .collect::<Vec<_>>();
        let confidences = self
            .confidence
            .forward(&Tensor::cat(&feature_refs, 0)?)?
            .to_dtype(DType::F32)?
            .squeeze(D::Minus1)?;
        let token_refs = t
            .token_tensors
            .iter()
            .chain(t.alt_token_tensors.iter())
            .collect::<Vec<_>>();
        let tokens_f32 = Tensor::cat(&token_refs, 0)?.to_dtype(DType::F32)?;
        Ok(Tensor::cat(&[&confidences, &tokens_f32], 0)?)
    }

    fn propose_inner(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
        diagnostics: bool,
        branch: bool,
    ) -> Result<DraftProposal> {
        let t = self.propose_tensors(anchor_token, anchor_pos, gamma, branch, diagnostics)?;
        // Single host readback: confidences and token ids ride one buffer.
        let pack_start = self.propose_timing.then(std::time::Instant::now);
        let packed_dev = self.pack_proposal(&t)?;
        let pack_ms = pack_start
            .map(|t0| -> Result<f64> {
                self.device.synchronize()?;
                Ok(t0.elapsed().as_secs_f64() * 1e3)
            })
            .transpose()?;
        let read_start = self.propose_timing.then(std::time::Instant::now);
        let packed = packed_dev.to_device(&Device::Cpu)?.to_vec1::<f32>()?;
        if let (Some(t0), Some(pack)) = (read_start, pack_ms) {
            eprintln!(
                "propose-ladder gamma={gamma}: pack {pack:.3} ms, readback {:.3} ms",
                t0.elapsed().as_secs_f64() * 1e3
            );
        }
        let n_alt = t.alt_token_tensors.len();
        let (conf_all, token_vals) =
            packed.split_at(gamma + if branch && gamma > 0 { gamma } else { 0 });
        let (confidence_logits, alt_confidence_logits) = conf_all.split_at(gamma);
        let (token_main, token_alt) = token_vals.split_at(gamma);
        let tokens = token_main.iter().map(|v| *v as u32).collect::<Vec<_>>();
        let alt_tokens = token_alt[..n_alt].iter().map(|v| *v as u32).collect::<Vec<_>>();
        let alt_confidence_logits = alt_confidence_logits.to_vec();
        let confidence_logits = confidence_logits.to_vec();
        let corrected_logits = if diagnostics {
            let corrected_refs = t.corrected.iter().collect::<Vec<_>>();
            Some(Tensor::cat(&corrected_refs, 0)?.unsqueeze(0)?)
        } else {
            None
        };
        Ok(DraftProposal {
            tokens,
            confidence_logits,
            alt_tokens,
            alt_confidence_logits,
            block_hidden: diagnostics.then_some(t.block_hidden),
            base_logits: diagnostics.then_some(t.base_logits),
            corrected_logits,
        })
    }

    /// Device-resident proposal for deferred-drain scheduling (on-device
    /// chunk assembly): the token chain stays on device for the verify-chunk
    /// cat, and the packed confidences/ids buffer is read back only after
    /// the verify chunk is enqueued — draft and verify then share ONE
    /// pipeline drain instead of paying the ~1-2ms OS wait twice per round.
    pub fn propose_device(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
    ) -> Result<DeviceProposal> {
        let t = self.propose_tensors(anchor_token, anchor_pos, gamma, false, false)?;
        let token_refs = t.token_tensors.iter().collect::<Vec<_>>();
        let tokens_dev = Tensor::cat(&token_refs, 0)?;
        let packed = self.pack_proposal(&t)?;
        Ok(DeviceProposal {
            packed,
            tokens_dev,
            gamma,
        })
    }
}

/// Un-materialized device tensors of one proposal (see
/// [`DsparkDrafter::propose_tensors`]).
struct ProposalTensors {
    token_tensors: Vec<Tensor>,
    alt_token_tensors: Vec<Tensor>,
    features: Vec<Tensor>,
    alt_features: Vec<Tensor>,
    corrected: Vec<Tensor>,
    block_hidden: Tensor,
    base_logits: Tensor,
}

/// A proposal whose tokens/confidences are still on device. `tokens_dev`
/// feeds the on-device verify-chunk cat; `packed` ([conf(gamma) |
/// tokens_f32(gamma)]) is read back together with the verify targets so the
/// round pays a single drain.
pub struct DeviceProposal {
    pub packed: Tensor,
    pub tokens_dev: Tensor,
    pub gamma: usize,
}

#[cfg(test)]
mod gguf_drafter_tests {
    use super::*;
    use crate::model_ctx::ModelCtx;

    // Loads the shipped Bonsai DSpark drafter GGUF and runs one full propose
    // (backbone + log-SNR conditioning + Markov chain + confidence head) over a
    // dummy target context, validating the GGUF loader + forward plumbing.
    #[test]
    fn bonsai_dspark_drafter_smoke() -> Result<()> {
        let path = std::path::PathBuf::from(format!(
            "{}/models/Ternary-Bonsai-27B/Ternary-Bonsai-27B-dspark-Q4_1.gguf",
            std::env::var("HOME").unwrap_or_default()
        ));
        if !path.exists() {
            eprintln!("skip: drafter not present");
            return Ok(());
        }
        let device = match Device::new_metal(0) {
            Ok(d) => d,
            Err(_) => {
                eprintln!("skip: no metal device");
                return Ok(());
            }
        };
        let gguf = crate::gguf::GgufFile::open(&path)?;
        let ctx = ModelCtx::default();
        let mut drafter = DsparkDrafter::load_gguf(&gguf, &device, DType::BF16, &ctx, false)?;
        assert_eq!(drafter.config.block_size, 4);
        assert_eq!(drafter.config.target_layer_ids, vec![1, 16, 31, 46, 61]);
        assert!(drafter.config.log_snr_conditioning);
        assert!(drafter.log_snr_bias.is_some());

        let bs = drafter.config.block_size;
        let cap = drafter.config.target_layer_ids.len() * drafter.config.hidden_size;
        let raw_ctx = Tensor::zeros((1, 1, cap), DType::BF16, &device)?;
        drafter.append_context(&raw_ctx, 0)?;
        let proposal = drafter.propose(1u32, 1, bs)?;
        assert_eq!(proposal.tokens.len(), bs);
        eprintln!("drafter smoke ok: tokens {:?}", proposal.tokens);
        Ok(())
    }
}
