//! Candle port of the DSpark drafter (DeepSpec Qwen3DSparkModel inference).
//!
//! Mirrors deepspec/modeling/dspark/qwen3/modeling.py exactly: a small
//! full-attention transformer whose K/V are the fused target context
//! prepended to the draft block, per-head QK-RMSNorm applied before RoPE,
//! bidirectional attention with no mask, a low-rank Markov bias sampled left
//! to right, and a linear confidence head over [h_k ; W1[x_{k-1}]].
//!
//! Verified against a fixture generated by the pinned training environment
//! (`dspark-drafter-parity`); the drafter keeps per-layer caches of the
//! projected context so multi-round runners only project newly committed
//! positions.

use std::fs::File;
use std::path::Path;

use anyhow::{Context, Result};
use candle::{DType, Device, IndexOp, Module, Tensor, D};
use candle_nn::{Linear, VarBuilder};
use serde::Deserialize;

use crate::quantized_linear::MixedLinear;
use crate::qwen35::TruncatableKvCache;

#[derive(Clone, Debug, Deserialize)]
pub struct DsparkRopeParameters {
    pub rope_theta: f64,
}

fn default_markov_head_type() -> String {
    "vanilla".to_string()
}
fn default_true() -> bool {
    true
}

#[derive(Clone, Debug, Deserialize)]
pub struct DsparkConfig {
    pub vocab_size: usize,
    pub hidden_size: usize,
    pub intermediate_size: usize,
    pub num_hidden_layers: usize,
    pub num_attention_heads: usize,
    pub num_key_value_heads: usize,
    pub head_dim: usize,
    pub rms_norm_eps: f64,
    pub block_size: usize,
    pub mask_token_id: u32,
    pub markov_rank: usize,
    pub target_layer_ids: Vec<usize>,
    pub rope_parameters: DsparkRopeParameters,
    // Head-variant switches: the port implements exactly vanilla Markov +
    // markov-feature confidence; loading must fail loudly on anything else
    // rather than ignore gate_proj/joint_proj tensors and drift silently.
    #[serde(default = "default_markov_head_type")]
    pub markov_head_type: String,
    #[serde(default = "default_true")]
    pub enable_confidence_head: bool,
    #[serde(default = "default_true")]
    pub confidence_head_with_markov: bool,
}

impl DsparkConfig {
    pub fn from_dir(dir: &Path) -> Result<Self> {
        let path = dir.join("config.json");
        let file =
            File::open(&path).with_context(|| format!("open drafter config {}", path.display()))?;
        serde_json::from_reader(file)
            .with_context(|| format!("parse drafter config {}", path.display()))
    }
}

/// Standard Qwen3 RMSNorm (weight * x_hat, no zero-centering), routed through
/// the fused Metal kernel (1 dispatch, F32 accumulation inside). The drafter
/// only ever normalizes model-dtype activations, so a single dtype-matched
/// weight suffices.
#[derive(Clone, Debug)]
struct RmsNorm {
    weight: Tensor,
    eps: f64,
}

impl RmsNorm {
    fn load(vb: &VarBuilder, name: &str, size: usize, eps: f64) -> Result<Self> {
        Ok(Self {
            weight: vb.get(size, name)?,
            eps,
        })
    }

    fn forward(&self, xs: &Tensor) -> candle::Result<Tensor> {
        let xs = if xs.is_contiguous() {
            xs.clone()
        } else {
            xs.contiguous()?
        };
        candle_nn::ops::rms_norm(&xs, &self.weight, self.eps as f32)
    }
}

/// Full-head-dim rotary at the checkpoint's theta. Training's Qwen3 rope path
/// ignores partial_rotary_factor (verified: 128 inv_freq entries for head_dim
/// 256), so the table spans the whole head dimension.
#[derive(Clone, Debug)]
struct Rotary {
    cos: Tensor,
    sin: Tensor,
}

const ROTARY_TABLE_LEN: usize = 16384;

impl Rotary {
    fn new(head_dim: usize, theta: f64, dtype: DType, device: &Device) -> Result<Self> {
        let inv_freq: Vec<f32> = (0..head_dim)
            .step_by(2)
            .map(|i| 1f32 / (theta as f32).powf(i as f32 / head_dim as f32))
            .collect();
        let inv_freq = Tensor::from_vec(inv_freq, (1, head_dim / 2), device)?;
        let t = Tensor::arange(0u32, ROTARY_TABLE_LEN as u32, device)?
            .to_dtype(DType::F32)?
            .reshape((ROTARY_TABLE_LEN, 1))?;
        let freqs = t.matmul(&inv_freq)?;
        // HF convention: emb = cat(freqs, freqs) over the last dim.
        let emb = Tensor::cat(&[&freqs, &freqs], D::Minus1)?;
        Ok(Self {
            cos: emb.cos()?.to_dtype(dtype)?,
            sin: emb.sin()?.to_dtype(dtype)?,
        })
    }

    /// Applies rotation to [b, heads, seq, head_dim] at absolute positions
    /// start..start+seq (HF rotate_half formulation).
    fn apply(&self, xs: &Tensor, start: usize) -> candle::Result<Tensor> {
        let (_, _, seq_len, head_dim) = xs.dims4()?;
        if start + seq_len > ROTARY_TABLE_LEN {
            candle::bail!(
                "rotary table too short: need {} > {ROTARY_TABLE_LEN}",
                start + seq_len
            );
        }
        let cos = self.cos.narrow(0, start, seq_len)?;
        let sin = self.sin.narrow(0, start, seq_len)?;
        let half = head_dim / 2;
        let x1 = xs.narrow(D::Minus1, 0, half)?;
        let x2 = xs.narrow(D::Minus1, half, half)?;
        let rotated = Tensor::cat(&[&x2.neg()?, &x1], D::Minus1)?;
        xs.broadcast_mul(&cos)?
            .add(&rotated.broadcast_mul(&sin)?)
    }
}

#[derive(Clone, Debug)]
struct DraftLayer {
    q_proj: Linear,
    k_proj: Linear,
    v_proj: Linear,
    o_proj: Linear,
    q_norm: RmsNorm,
    k_norm: RmsNorm,
    gate_proj: Linear,
    up_proj: Linear,
    down_proj: Linear,
    input_layernorm: RmsNorm,
    post_attention_layernorm: RmsNorm,
    // Projected fused-context K/V at their absolute positions (roped), in a
    // grow-on-demand buffer: appends write only the new rows, and propose()
    // appends the block rows then truncates back — no per-round copies of
    // the whole context (the old Tensor::cat pattern was O(T) per round and
    // O(T^2) over a run).
    ctx: TruncatableKvCache,
}

impl DraftLayer {
    fn clear_context(&mut self) {
        self.ctx
            .truncate(0)
            .expect("truncate to zero cannot fail");
    }
}

pub struct DsparkDrafter {
    pub config: DsparkConfig,
    embed_tokens: Tensor,
    layers: Vec<DraftLayer>,
    norm: RmsNorm,
    fc: Linear,
    hidden_norm: RmsNorm,
    lm_head: MixedLinear,
    markov_w1: Tensor,
    markov_w2: MixedLinear,
    confidence: Linear,
    rotary: Rotary,
    // FR-Spec draft-vocabulary restriction: when set, lm_head and markov_w2
    // hold only these rows (rank order), and proposal argmaxes remap through
    // this id table. Committed output is unaffected (verification is exact);
    // only draft cost and tau move.
    draft_vocab_ids: Option<Tensor>,
    device: Device,
    dtype: DType,
}

#[derive(Clone, Debug)]
pub struct DraftProposal {
    pub tokens: Vec<u32>,
    pub confidence_logits: Vec<f32>,
    /// Alternate chain branching at position 0 from the runner-up Markov
    /// token — nearly free by construction (base_logits\[k\] is branch-
    /// independent; only the Markov bias chains), for tree speculation.
    pub alt_tokens: Vec<u32>,
    pub alt_confidence_logits: Vec<f32>,
    /// Populated only by `propose_with_diagnostics` (parity harness); the
    /// hot loop skips materializing them (~0.2 ms/round of vocab-wide cats).
    pub block_hidden: Option<Tensor>,
    pub base_logits: Option<Tensor>,
    pub corrected_logits: Option<Tensor>,
}

fn maybe_slice_rows(weight: Tensor, ids: Option<&[u32]>) -> Result<Tensor> {
    match ids {
        None => Ok(weight),
        Some(ids) => {
            let idx = Tensor::from_slice(ids, ids.len(), weight.device())?;
            Ok(weight.index_select(&idx, 0)?.contiguous()?)
        }
    }
}

fn quantize_or_dense(
    weight: Tensor,
    dtype: Option<candle::quantized::GgmlDType>,
    device: &Device,
) -> Result<MixedLinear> {
    match dtype {
        None => Ok(MixedLinear::dense(Linear::new(weight, None))),
        Some(ggml) => {
            let cpu_f32 = weight
                .to_dtype(DType::F32)?
                .to_device(&Device::Cpu)?;
            let q = candle::quantized::QTensor::quantize_onto(&cpu_f32, ggml, device)?;
            Ok(MixedLinear::from_qtensor(q)?)
        }
    }
}

impl DsparkDrafter {
    pub fn load(dir: &Path, device: &Device, dtype: DType) -> Result<Self> {
        Self::load_with_options(dir, device, dtype, None)
    }

    /// `quantize_heads` post-hoc quantizes the two 248k-vocab weight reads
    /// (lm_head, markov_w2) at load — no artifact, no retraining. markov_w1
    /// stays BF16 (index_select gather) and the confidence head stays dense.
    /// The risk surface is tau, not correctness: drafts are target-verified.
    pub fn load_with_options(
        dir: &Path,
        device: &Device,
        dtype: DType,
        quantize_heads: Option<candle::quantized::GgmlDType>,
    ) -> Result<Self> {
        Self::load_with_draft_vocab(dir, device, dtype, quantize_heads, None)
    }

    /// `draft_vocab`: FR-Spec top-k token ids (rank order). The vocab-wide
    /// draft heads (lm_head, markov_w2) are sliced to these rows before any
    /// quantization; markov_w1, the embedding and the confidence head keep
    /// the full vocabulary (they index by committed-token id, which need not
    /// be inside the draft vocabulary).
    pub fn load_with_draft_vocab(
        dir: &Path,
        device: &Device,
        dtype: DType,
        quantize_heads: Option<candle::quantized::GgmlDType>,
        draft_vocab: Option<&[u32]>,
    ) -> Result<Self> {
        let config = DsparkConfig::from_dir(dir)?;
        if config.markov_head_type != "vanilla"
            || !config.enable_confidence_head
            || !config.confidence_head_with_markov
        {
            anyhow::bail!(
                "drafter checkpoint wants markov_head_type={:?} \
                 enable_confidence_head={} confidence_head_with_markov={}; this \
                 port implements only vanilla + markov-feature confidence",
                config.markov_head_type,
                config.enable_confidence_head,
                config.confidence_head_with_markov,
            );
        }
        let weights = dir.join("model.safetensors");
        let vb = unsafe {
            VarBuilder::from_mmaped_safetensors(&[weights.clone()], dtype, device)
                .with_context(|| format!("mmap drafter weights {}", weights.display()))?
        };
        let h = config.hidden_size;
        let heads = config.num_attention_heads;
        let kv_heads = config.num_key_value_heads;
        let head_dim = config.head_dim;
        let eps = config.rms_norm_eps;

        let mut layers = Vec::with_capacity(config.num_hidden_layers);
        for i in 0..config.num_hidden_layers {
            let p = format!("layers.{i}");
            layers.push(DraftLayer {
                q_proj: Linear::new(vb.get((heads * head_dim, h), &format!("{p}.self_attn.q_proj.weight"))?, None),
                k_proj: Linear::new(vb.get((kv_heads * head_dim, h), &format!("{p}.self_attn.k_proj.weight"))?, None),
                v_proj: Linear::new(vb.get((kv_heads * head_dim, h), &format!("{p}.self_attn.v_proj.weight"))?, None),
                o_proj: Linear::new(vb.get((h, heads * head_dim), &format!("{p}.self_attn.o_proj.weight"))?, None),
                q_norm: RmsNorm::load(&vb, &format!("{p}.self_attn.q_norm.weight"), head_dim, eps)?,
                k_norm: RmsNorm::load(&vb, &format!("{p}.self_attn.k_norm.weight"), head_dim, eps)?,
                gate_proj: Linear::new(vb.get((config.intermediate_size, h), &format!("{p}.mlp.gate_proj.weight"))?, None),
                up_proj: Linear::new(vb.get((config.intermediate_size, h), &format!("{p}.mlp.up_proj.weight"))?, None),
                down_proj: Linear::new(vb.get((h, config.intermediate_size), &format!("{p}.mlp.down_proj.weight"))?, None),
                input_layernorm: RmsNorm::load(&vb, &format!("{p}.input_layernorm.weight"), h, eps)?,
                post_attention_layernorm: RmsNorm::load(&vb, &format!("{p}.post_attention_layernorm.weight"), h, eps)?,
                ctx: TruncatableKvCache::new(),
            });
        }

        Ok(Self {
            embed_tokens: vb.get((config.vocab_size, h), "embed_tokens.weight")?,
            norm: RmsNorm::load(&vb, "norm.weight", h, eps)?,
            fc: Linear::new(
                vb.get((h, config.target_layer_ids.len() * h), "fc.weight")?,
                None,
            ),
            hidden_norm: RmsNorm::load(&vb, "hidden_norm.weight", h, eps)?,
            lm_head: quantize_or_dense(
                maybe_slice_rows(
                    vb.get((config.vocab_size, h), "lm_head.weight")?,
                    draft_vocab,
                )?,
                quantize_heads,
                device,
            )?,
            markov_w1: vb.get((config.vocab_size, config.markov_rank), "markov_head.markov_w1.weight")?,
            markov_w2: quantize_or_dense(
                maybe_slice_rows(
                    vb.get((config.vocab_size, config.markov_rank), "markov_head.markov_w2.weight")?,
                    draft_vocab,
                )?,
                quantize_heads,
                device,
            )?,
            draft_vocab_ids: draft_vocab
                .map(|ids| Tensor::from_slice(ids, ids.len(), device))
                .transpose()?,
            confidence: Linear::new(
                vb.get((1, h + config.markov_rank), "confidence_head.proj.weight")?,
                Some(vb.get(1, "confidence_head.proj.bias")?),
            ),
            rotary: Rotary::new(head_dim, config.rope_parameters.rope_theta, dtype, device)?,
            layers,
            device: device.clone(),
            dtype,
            config,
        })
    }

    pub fn clear_context(&mut self) {
        for layer in &mut self.layers {
            layer.clear_context();
        }
    }

    fn embed(&self, ids: &[u32]) -> candle::Result<Tensor> {
        let ids = Tensor::from_slice(ids, ids.len(), &self.device)?;
        self.embed_tokens.index_select(&ids, 0)?.unsqueeze(0)
    }

    /// Fuses raw capture-layer concat states ([1, m, capture*hidden]) and
    /// appends per-layer projected K/V at absolute positions
    /// start_pos..start_pos+m.
    pub fn append_context(&mut self, raw_ctx: &Tensor, start_pos: usize) -> Result<()> {
        let raw_ctx = raw_ctx.to_dtype(self.dtype)?;
        let fused = self.hidden_norm.forward(&self.fc.forward(&raw_ctx)?)?;
        let (b, m, _) = fused.dims3()?;
        let kv_heads = self.config.num_key_value_heads;
        let head_dim = self.config.head_dim;
        for layer in &mut self.layers {
            let k = layer
                .k_norm
                .forward(&layer.k_proj.forward(&fused)?.reshape((b, m, kv_heads, head_dim))?)?
                .transpose(1, 2)?
                .contiguous()?;
            let k = self.rotary.apply(&k, start_pos)?;
            let v_new = layer
                .v_proj
                .forward(&fused)?
                .reshape((b, m, kv_heads, head_dim))?
                .transpose(1, 2)?
                .contiguous()?;
            if layer.ctx.len() != start_pos {
                anyhow::bail!(
                    "drafter context length {} does not match append position {start_pos}",
                    layer.ctx.len()
                );
            }
            layer.ctx.append(&k.contiguous()?, &v_new)?;
        }
        Ok(())
    }

    /// One draft block at absolute positions anchor_pos..anchor_pos+block_size,
    /// attending bidirectionally over cached context + the block. The backbone
    /// ALWAYS runs on the full block_size positions — training only ever saw
    /// full blocks, and bidirectional attention makes every h_k depend on the
    /// trailing mask tokens, so a shortened block is out-of-distribution.
    /// Only the first `gamma` positions go through lm_head/Markov/confidence.
    pub fn propose(&mut self, anchor_token: u32, anchor_pos: usize, gamma: usize) -> Result<DraftProposal> {
        self.propose_inner(anchor_token, anchor_pos, gamma, false, false)
    }

    /// Also drafts the alternate chain branching at position 0 (runner-up
    /// Markov token) for tree speculation: ~1 extra Markov gemv per position.
    pub fn propose_branching(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
    ) -> Result<DraftProposal> {
        self.propose_inner(anchor_token, anchor_pos, gamma, false, true)
    }

    /// Parity-harness variant that also materializes block_hidden /
    /// base_logits / corrected_logits.
    pub fn propose_with_diagnostics(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
    ) -> Result<DraftProposal> {
        self.propose_inner(anchor_token, anchor_pos, gamma, true, false)
    }

    fn propose_inner(
        &mut self,
        anchor_token: u32,
        anchor_pos: usize,
        gamma: usize,
        diagnostics: bool,
        branch: bool,
    ) -> Result<DraftProposal> {
        let block = self.config.block_size;
        if gamma == 0 || gamma > block {
            anyhow::bail!("gamma {gamma} outside 1..={block}");
        }
        let mut ids = vec![self.config.mask_token_id; block];
        ids[0] = anchor_token;
        let mut hidden = self.embed(&ids)?;
        let (b, q_len, _) = hidden.dims3()?;
        let heads = self.config.num_attention_heads;
        let kv_heads = self.config.num_key_value_heads;
        let head_dim = self.config.head_dim;
        let scale = 1.0 / (head_dim as f64).sqrt();

        for layer in &mut self.layers {
            let residual = hidden.clone();
            let normed = layer.input_layernorm.forward(&hidden)?;
            let q = layer
                .q_norm
                .forward(&layer.q_proj.forward(&normed)?.reshape((b, q_len, heads, head_dim))?)?
                .transpose(1, 2)?
                .contiguous()?;
            let q = self.rotary.apply(&q, anchor_pos)?;
            let k_new = layer
                .k_norm
                .forward(&layer.k_proj.forward(&normed)?.reshape((b, q_len, kv_heads, head_dim))?)?
                .transpose(1, 2)?
                .contiguous()?;
            let k_new = self.rotary.apply(&k_new, anchor_pos)?;
            let v_new = layer
                .v_proj
                .forward(&normed)?
                .reshape((b, q_len, kv_heads, head_dim))?
                .transpose(1, 2)?
                .contiguous()?;
            // Block rows are appended into the context buffer for the
            // attention call and truncated straight back out: bidirectional
            // attention over [ctx | block] with zero copies of the context.
            // The fused SDPA kernel handles GQA natively (no repeat_kv).
            let prev_len = layer.ctx.len();
            let (k_all, v_all) = layer
                .ctx
                .append(&k_new.contiguous()?, &v_new)?;
            let out = candle_nn::ops::sdpa(
                &q.contiguous()?,
                &k_all,
                &v_all,
                None,
                false,
                scale as f32,
                1.0,
            )?;
            layer.ctx.truncate(prev_len)?;
            let out = out
                .transpose(1, 2)?
                .reshape((b, q_len, heads * head_dim))?;
            hidden = (residual + layer.o_proj.forward(&out)?)?;

            let residual = hidden.clone();
            let normed = layer.post_attention_layernorm.forward(&hidden)?;
            let gated = (layer.gate_proj.forward(&normed)?.silu()? * layer.up_proj.forward(&normed)?)?;
            hidden = (residual + layer.down_proj.forward(&gated)?)?;
        }
        // Heads read only the proposal prefix; narrowing before lm_head skips
        // the vocab projection for the unused trailing block positions.
        let block_hidden = self.norm.forward(&hidden)?.narrow(1, 0, gamma)?;
        let base_logits = self.lm_head.forward(&block_hidden.contiguous()?)?;

        // Left-to-right greedy Markov sampling; corrected logits define p_d.
        // The token chain stays on device (argmax feeds the next index_select
        // directly) so the loop enqueues without host syncs; tokens and
        // confidences are read back once at the end.
        let mut prev_id = Tensor::from_slice(&[anchor_token], 1, &self.device)?;
        let mut token_tensors = Vec::with_capacity(gamma);
        let mut corrected = Vec::with_capacity(gamma);
        let mut features = Vec::with_capacity(gamma);
        let mut sub_argmax0: Option<Tensor> = None;
        for k in 0..gamma {
            let prev_emb = self.markov_w1.index_select(&prev_id, 0)?;
            let bias = self.markov_w2.forward(&prev_emb)?;
            let step = (base_logits.i((0, k))?.unsqueeze(0)? + &bias)?;
            let sub_token = step.to_dtype(DType::F32)?.argmax(D::Minus1)?;
            // Draft-vocab argmaxes index the sliced rows; remap to global ids
            // (one device-side gather) so the Markov chain and readback stay
            // in real token space.
            let token = match &self.draft_vocab_ids {
                Some(ids) => ids.index_select(&sub_token, 0)?,
                None => sub_token.clone(),
            };
            if k == 0 {
                sub_argmax0 = Some(sub_token);
            }
            let h_k = block_hidden.i((0, k))?.unsqueeze(0)?;
            features.push(Tensor::cat(&[&h_k, &prev_emb.to_dtype(self.dtype)?], D::Minus1)?);
            corrected.push(step);
            token_tensors.push(token.clone());
            prev_id = token;
        }
        // Alternate chain: branch at position 0 from the runner-up Markov
        // token; base_logits rows are branch-independent, so this is one
        // masked-argmax plus gamma-1 extra Markov steps.
        let mut alt_token_tensors = Vec::new();
        let mut alt_features = Vec::new();
        if branch && gamma > 0 {
            let step0 = corrected[0].to_dtype(DType::F32)?.squeeze(0)?;
            let neg = Tensor::full(-1e30f32, 1, &self.device)?;
            // Keep the id rank-1 like the main chain's argmax(Minus1) output:
            // markov_w1.index_select rejects rank-0 indices. The mask index
            // lives in the (possibly sliced) logit space; the winner remaps
            // to a global id afterwards.
            let mask_idx = sub_argmax0
                .as_ref()
                .expect("main chain populated position 0")
                .clone();
            let second_sub = step0
                .index_add(&mask_idx, &neg, 0)?
                .argmax(0)?
                .unsqueeze(0)?;
            let second = match &self.draft_vocab_ids {
                Some(ids) => ids.index_select(&second_sub, 0)?,
                None => second_sub,
            };
            let mut prev = second.clone();
            alt_token_tensors.push(second);
            for k in 0..gamma {
                let prev_emb = self.markov_w1.index_select(&prev, 0)?;
                let h_k = block_hidden.i((0, k))?.unsqueeze(0)?;
                alt_features
                    .push(Tensor::cat(&[&h_k, &prev_emb.to_dtype(self.dtype)?], D::Minus1)?);
                if k + 1 < gamma {
                    let bias = self.markov_w2.forward(&prev_emb)?;
                    let step = (base_logits.i((0, k + 1))?.unsqueeze(0)? + &bias)?;
                    let sub = step.to_dtype(DType::F32)?.argmax(D::Minus1)?;
                    let token = match &self.draft_vocab_ids {
                        Some(ids) => ids.index_select(&sub, 0)?,
                        None => sub,
                    };
                    alt_token_tensors.push(token.clone());
                    prev = token;
                }
            }
        }

        let feature_refs = features.iter().chain(alt_features.iter()).collect::<Vec<_>>();
        let confidences = self
            .confidence
            .forward(&Tensor::cat(&feature_refs, 0)?)?
            .to_dtype(DType::F32)?
            .squeeze(D::Minus1)?;
        // Single host readback: confidences and token ids ride one buffer
        // (u32 < 2^24 is exact in f32), halving the per-proposal sync count.
        let token_refs = token_tensors
            .iter()
            .chain(alt_token_tensors.iter())
            .collect::<Vec<_>>();
        let tokens_f32 = Tensor::cat(&token_refs, 0)?.to_dtype(DType::F32)?;
        let packed = Tensor::cat(&[&confidences, &tokens_f32], 0)?
            .to_device(&Device::Cpu)?
            .to_vec1::<f32>()?;
        let n_alt = alt_token_tensors.len();
        let (conf_all, token_vals) = packed.split_at(gamma + if branch && gamma > 0 { gamma } else { 0 });
        let (confidence_logits, alt_confidence_logits) = conf_all.split_at(gamma);
        let (token_main, token_alt) = token_vals.split_at(gamma);
        let tokens = token_main.iter().map(|v| *v as u32).collect::<Vec<_>>();
        let alt_tokens = token_alt[..n_alt].iter().map(|v| *v as u32).collect::<Vec<_>>();
        let alt_confidence_logits = alt_confidence_logits.to_vec();
        let confidence_logits = confidence_logits.to_vec();
        let corrected_logits = if diagnostics {
            let corrected_refs = corrected.iter().collect::<Vec<_>>();
            Some(Tensor::cat(&corrected_refs, 0)?.unsqueeze(0)?)
        } else {
            None
        };
        Ok(DraftProposal {
            tokens,
            confidence_logits,
            alt_tokens,
            alt_confidence_logits,
            block_hidden: diagnostics.then_some(block_hidden),
            base_logits: diagnostics.then_some(base_logits),
            corrected_logits,
        })
    }
}
